// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ondeFFI)
    import ondeFFI
#endif

extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    fileprivate init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    fileprivate static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    fileprivate static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_onde_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    fileprivate func deallocate() {
        try! rustCall { ffi_onde_rustbuffer_free(self, $0) }
    }
}

extension ForeignBytes {
    fileprivate init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

extension Data {
    fileprivate init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws
    -> T
{
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range) })
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws
    -> [UInt8]
{
    let range = reader.offset..<(reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S)
where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow:
            return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case .rustPanic(let message): return message
        }
    }
}

extension NSLock {
    fileprivate func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

extension RustCallStatus {
    fileprivate init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOndeInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/// On-device LLM chat inference engine — UniFFI-exported wrapper.
///
/// This is the primary entry point for Swift / Kotlin consumers.  It wraps
/// [`ChatEngine`] with FFI-safe method signatures (no generics, no Rust
/// channels, concrete `String` parameters).
///
/// Construct with [`OndeChatEngine::new()`].  The engine starts with no
/// model loaded — call [`load_gguf_model`] or [`load_default_model`] first.
public protocol OndeChatEngineProtocol: AnyObject, Sendable {

    /**
     * Clear the conversation history but keep the model loaded.
     *
     * Returns the number of turns that were removed.
     */
    func clearHistory() async -> UInt64

    /**
     * Clear the system prompt.
     */
    func clearSystemPrompt() async

    /**
     * Run inference on an explicit list of messages WITHOUT modifying the
     * engine's internal history.
     *
     * Useful for one-shot prompts (e.g. prompt enhancement).
     */
    func generate(messages: [ChatMessage], sampling: SamplingConfig?) async throws
        -> InferenceResult

    /**
     * Get a copy of the full conversation history.
     */
    func history() async -> [ChatMessage]

    /**
     * Get a snapshot of the engine's current state.
     */
    func info() async -> EngineInfo

    /**
     * Check whether a model is currently loaded.
     */
    func isLoaded() async -> Bool

    /**
     * Load the platform-appropriate default model.
     *
     * - tvOS / iOS / Android → Qwen 2.5 1.5B (~941 MB)
     * - macOS / Windows / Linux → Qwen 2.5 3B (~1.93 GB)
     *
     * Returns the wall-clock loading time in seconds.
     */
    func loadDefaultModel(systemPrompt: String?, sampling: SamplingConfig?) async throws -> Double

    /**
     * Load a GGUF model into the engine.
     *
     * If a model is already loaded it will be unloaded first.
     *
     * Returns the wall-clock loading time in seconds.
     */
    func loadGgufModel(config: GgufModelConfig, systemPrompt: String?, sampling: SamplingConfig?)
        async throws -> Double

    /**
     * Append a message to history without running inference.
     */
    func pushHistory(message: ChatMessage) async

    /**
     * Send a user message and receive a complete assistant reply.
     *
     * The user message and assistant reply are automatically appended to
     * the conversation history on success.
     */
    func sendMessage(message: String) async throws -> InferenceResult

    /**
     * Replace the sampling configuration.
     */
    func setSampling(sampling: SamplingConfig) async

    /**
     * Set or replace the system prompt.
     */
    func setSystemPrompt(prompt: String) async

    /**
     * Unload the current model, freeing all memory.
     *
     * Returns the display name of the model that was unloaded, or `nil`
     * if no model was loaded.
     */
    func unloadModel() async -> String?

}
/// On-device LLM chat inference engine — UniFFI-exported wrapper.
///
/// This is the primary entry point for Swift / Kotlin consumers.  It wraps
/// [`ChatEngine`] with FFI-safe method signatures (no generics, no Rust
/// channels, concrete `String` parameters).
///
/// Construct with [`OndeChatEngine::new()`].  The engine starts with no
/// model loaded — call [`load_gguf_model`] or [`load_default_model`] first.
open class OndeChatEngine: OndeChatEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_onde_fn_clone_ondechatengine(self.handle, $0) }
    }
    /**
     * Create a new engine with no model loaded.
     */
    public convenience init() {
        let handle =
            try! rustCall {
                uniffi_onde_fn_constructor_ondechatengine_new(
                    $0
                )
            }
        self.init(unsafeFromHandle: handle)
    }

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_onde_fn_free_ondechatengine(handle, $0) }
    }

    /**
     * Clear the conversation history but keep the model loaded.
     *
     * Returns the number of turns that were removed.
     */
    open func clearHistory() async -> UInt64 {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_clear_history(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_u64,
                completeFunc: ffi_onde_rust_future_complete_u64,
                freeFunc: ffi_onde_rust_future_free_u64,
                liftFunc: FfiConverterUInt64.lift,
                errorHandler: nil

            )
    }

    /**
     * Clear the system prompt.
     */
    open func clearSystemPrompt() async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_clear_system_prompt(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_void,
                completeFunc: ffi_onde_rust_future_complete_void,
                freeFunc: ffi_onde_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil

            )
    }

    /**
     * Run inference on an explicit list of messages WITHOUT modifying the
     * engine's internal history.
     *
     * Useful for one-shot prompts (e.g. prompt enhancement).
     */
    open func generate(messages: [ChatMessage], sampling: SamplingConfig?) async throws
        -> InferenceResult
    {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_generate(
                        self.uniffiCloneHandle(),
                        FfiConverterSequenceTypeChatMessage.lower(messages),
                        FfiConverterOptionTypeSamplingConfig.lower(sampling)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_rust_buffer,
                completeFunc: ffi_onde_rust_future_complete_rust_buffer,
                freeFunc: ffi_onde_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeInferenceResult_lift,
                errorHandler: FfiConverterTypeInferenceError_lift
            )
    }

    /**
     * Get a copy of the full conversation history.
     */
    open func history() async -> [ChatMessage] {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_history(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_rust_buffer,
                completeFunc: ffi_onde_rust_future_complete_rust_buffer,
                freeFunc: ffi_onde_rust_future_free_rust_buffer,
                liftFunc: FfiConverterSequenceTypeChatMessage.lift,
                errorHandler: nil

            )
    }

    /**
     * Get a snapshot of the engine's current state.
     */
    open func info() async -> EngineInfo {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_info(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_rust_buffer,
                completeFunc: ffi_onde_rust_future_complete_rust_buffer,
                freeFunc: ffi_onde_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeEngineInfo_lift,
                errorHandler: nil

            )
    }

    /**
     * Check whether a model is currently loaded.
     */
    open func isLoaded() async -> Bool {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_is_loaded(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_i8,
                completeFunc: ffi_onde_rust_future_complete_i8,
                freeFunc: ffi_onde_rust_future_free_i8,
                liftFunc: FfiConverterBool.lift,
                errorHandler: nil

            )
    }

    /**
     * Load the platform-appropriate default model.
     *
     * - tvOS / iOS / Android → Qwen 2.5 1.5B (~941 MB)
     * - macOS / Windows / Linux → Qwen 2.5 3B (~1.93 GB)
     *
     * Returns the wall-clock loading time in seconds.
     */
    open func loadDefaultModel(systemPrompt: String?, sampling: SamplingConfig?) async throws
        -> Double
    {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_load_default_model(
                        self.uniffiCloneHandle(),
                        FfiConverterOptionString.lower(systemPrompt),
                        FfiConverterOptionTypeSamplingConfig.lower(sampling)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_f64,
                completeFunc: ffi_onde_rust_future_complete_f64,
                freeFunc: ffi_onde_rust_future_free_f64,
                liftFunc: FfiConverterDouble.lift,
                errorHandler: FfiConverterTypeInferenceError_lift
            )
    }

    /**
     * Load a GGUF model into the engine.
     *
     * If a model is already loaded it will be unloaded first.
     *
     * Returns the wall-clock loading time in seconds.
     */
    open func loadGgufModel(
        config: GgufModelConfig, systemPrompt: String?, sampling: SamplingConfig?
    ) async throws -> Double {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_load_gguf_model(
                        self.uniffiCloneHandle(),
                        FfiConverterTypeGgufModelConfig_lower(config),
                        FfiConverterOptionString.lower(systemPrompt),
                        FfiConverterOptionTypeSamplingConfig.lower(sampling)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_f64,
                completeFunc: ffi_onde_rust_future_complete_f64,
                freeFunc: ffi_onde_rust_future_free_f64,
                liftFunc: FfiConverterDouble.lift,
                errorHandler: FfiConverterTypeInferenceError_lift
            )
    }

    /**
     * Append a message to history without running inference.
     */
    open func pushHistory(message: ChatMessage) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_push_history(
                        self.uniffiCloneHandle(),
                        FfiConverterTypeChatMessage_lower(message)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_void,
                completeFunc: ffi_onde_rust_future_complete_void,
                freeFunc: ffi_onde_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil

            )
    }

    /**
     * Send a user message and receive a complete assistant reply.
     *
     * The user message and assistant reply are automatically appended to
     * the conversation history on success.
     */
    open func sendMessage(message: String) async throws -> InferenceResult {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_send_message(
                        self.uniffiCloneHandle(),
                        FfiConverterString.lower(message)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_rust_buffer,
                completeFunc: ffi_onde_rust_future_complete_rust_buffer,
                freeFunc: ffi_onde_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeInferenceResult_lift,
                errorHandler: FfiConverterTypeInferenceError_lift
            )
    }

    /**
     * Replace the sampling configuration.
     */
    open func setSampling(sampling: SamplingConfig) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_set_sampling(
                        self.uniffiCloneHandle(),
                        FfiConverterTypeSamplingConfig_lower(sampling)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_void,
                completeFunc: ffi_onde_rust_future_complete_void,
                freeFunc: ffi_onde_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil

            )
    }

    /**
     * Set or replace the system prompt.
     */
    open func setSystemPrompt(prompt: String) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_set_system_prompt(
                        self.uniffiCloneHandle(),
                        FfiConverterString.lower(prompt)
                    )
                },
                pollFunc: ffi_onde_rust_future_poll_void,
                completeFunc: ffi_onde_rust_future_complete_void,
                freeFunc: ffi_onde_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil

            )
    }

    /**
     * Unload the current model, freeing all memory.
     *
     * Returns the display name of the model that was unloaded, or `nil`
     * if no model was loaded.
     */
    open func unloadModel() async -> String? {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_onde_fn_method_ondechatengine_unload_model(
                        self.uniffiCloneHandle()

                    )
                },
                pollFunc: ffi_onde_rust_future_poll_rust_buffer,
                completeFunc: ffi_onde_rust_future_complete_rust_buffer,
                freeFunc: ffi_onde_rust_future_free_rust_buffer,
                liftFunc: FfiConverterOptionString.lift,
                errorHandler: nil

            )
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeOndeChatEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = OndeChatEngine

    public static func lift(_ handle: UInt64) throws -> OndeChatEngine {
        return OndeChatEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: OndeChatEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> OndeChatEngine
    {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: OndeChatEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeOndeChatEngine_lift(_ handle: UInt64) throws -> OndeChatEngine {
    return try FfiConverterTypeOndeChatEngine.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeOndeChatEngine_lower(_ value: OndeChatEngine) -> UInt64 {
    return FfiConverterTypeOndeChatEngine.lower(value)
}

/// A single message in a conversation.
public struct ChatMessage: Equatable, Hashable {
    public var role: ChatRole
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(role: ChatRole, content: String) {
        self.role = role
        self.content = content
    }

}

#if compiler(>=6)
    extension ChatMessage: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatMessage
    {
        return
            try ChatMessage(
                role: FfiConverterTypeChatRole.read(from: &buf),
                content: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: ChatMessage, into buf: inout [UInt8]) {
        FfiConverterTypeChatRole.write(value.role, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lift(_ buf: RustBuffer) throws -> ChatMessage {
    return try FfiConverterTypeChatMessage.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lower(_ value: ChatMessage) -> RustBuffer {
    return FfiConverterTypeChatMessage.lower(value)
}

/// A point-in-time snapshot of the engine's state, suitable for status UIs.
///
/// Note: `history_length` is `u64` (not `usize`) for UniFFI compatibility.
public struct EngineInfo: Equatable, Hashable {
    public var status: EngineStatus
    /**
     * Display name of the currently loaded model, if any.
     */
    public var modelName: String?
    /**
     * Approximate memory footprint description, if a model is loaded.
     */
    public var approxMemory: String?
    /**
     * Number of conversation turns in the current history.
     */
    public var historyLength: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        status: EngineStatus,
        /**
         * Display name of the currently loaded model, if any.
         */
        modelName: String?,
        /**
         * Approximate memory footprint description, if a model is loaded.
         */
        approxMemory: String?,
        /**
         * Number of conversation turns in the current history.
         */
        historyLength: UInt64
    ) {
        self.status = status
        self.modelName = modelName
        self.approxMemory = approxMemory
        self.historyLength = historyLength
    }

}

#if compiler(>=6)
    extension EngineInfo: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineInfo {
        return
            try EngineInfo(
                status: FfiConverterTypeEngineStatus.read(from: &buf),
                modelName: FfiConverterOptionString.read(from: &buf),
                approxMemory: FfiConverterOptionString.read(from: &buf),
                historyLength: FfiConverterUInt64.read(from: &buf)
            )
    }

    public static func write(_ value: EngineInfo, into buf: inout [UInt8]) {
        FfiConverterTypeEngineStatus.write(value.status, into: &buf)
        FfiConverterOptionString.write(value.modelName, into: &buf)
        FfiConverterOptionString.write(value.approxMemory, into: &buf)
        FfiConverterUInt64.write(value.historyLength, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineInfo_lift(_ buf: RustBuffer) throws -> EngineInfo {
    return try FfiConverterTypeEngineInfo.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineInfo_lower(_ value: EngineInfo) -> RustBuffer {
    return FfiConverterTypeEngineInfo.lower(value)
}

/// Configuration for loading a GGUF model via mistral.rs.
///
/// This is the primary model format for on-device mobile/desktop inference
/// because GGUF files are pre-quantized and load at their compressed size,
/// avoiding the large memory spike of in-situ quantization.
public struct GgufModelConfig: Equatable, Hashable {
    /**
     * HuggingFace model repository ID, e.g. `"bartowski/Qwen2.5-1.5B-Instruct-GGUF"`.
     */
    public var modelId: String
    /**
     * GGUF filename(s) within the repository, e.g. `["Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"]`.
     */
    public var files: [String]
    /**
     * Optional: explicit tokenizer model ID (required on Android where GGUF
     * embedded tokenizers are not supported by the candle backend).
     */
    public var tokModelId: String?
    /**
     * Human-friendly display name, e.g. `"Qwen 2.5 1.5B"`.
     */
    public var displayName: String
    /**
     * Approximate memory footprint description, e.g. `"~941 MB (GGUF Q4_K_M)"`.
     */
    public var approxMemory: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * HuggingFace model repository ID, e.g. `"bartowski/Qwen2.5-1.5B-Instruct-GGUF"`.
         */
        modelId: String,
        /**
         * GGUF filename(s) within the repository, e.g. `["Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"]`.
         */
        files: [String],
        /**
         * Optional: explicit tokenizer model ID (required on Android where GGUF
         * embedded tokenizers are not supported by the candle backend).
         */
        tokModelId: String?,
        /**
         * Human-friendly display name, e.g. `"Qwen 2.5 1.5B"`.
         */
        displayName: String,
        /**
         * Approximate memory footprint description, e.g. `"~941 MB (GGUF Q4_K_M)"`.
         */
        approxMemory: String
    ) {
        self.modelId = modelId
        self.files = files
        self.tokModelId = tokModelId
        self.displayName = displayName
        self.approxMemory = approxMemory
    }

}

#if compiler(>=6)
    extension GgufModelConfig: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeGgufModelConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> GgufModelConfig
    {
        return
            try GgufModelConfig(
                modelId: FfiConverterString.read(from: &buf),
                files: FfiConverterSequenceString.read(from: &buf),
                tokModelId: FfiConverterOptionString.read(from: &buf),
                displayName: FfiConverterString.read(from: &buf),
                approxMemory: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: GgufModelConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.modelId, into: &buf)
        FfiConverterSequenceString.write(value.files, into: &buf)
        FfiConverterOptionString.write(value.tokModelId, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.approxMemory, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGgufModelConfig_lift(_ buf: RustBuffer) throws -> GgufModelConfig {
    return try FfiConverterTypeGgufModelConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGgufModelConfig_lower(_ value: GgufModelConfig) -> RustBuffer {
    return FfiConverterTypeGgufModelConfig.lower(value)
}

/// The result of a chat inference request.
public struct InferenceResult: Equatable, Hashable {
    /**
     * The generated assistant reply text.
     */
    public var text: String
    /**
     * Wall-clock duration of the inference in seconds.
     */
    public var durationSecs: Double
    /**
     * Human-readable duration string (e.g. `"2m 3.1s"` or `"4.5s"`).
     */
    public var durationDisplay: String
    /**
     * Finish reason reported by the model (e.g. `"stop"`, `"length"`).
     */
    public var finishReason: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The generated assistant reply text.
         */
        text: String,
        /**
         * Wall-clock duration of the inference in seconds.
         */
        durationSecs: Double,
        /**
         * Human-readable duration string (e.g. `"2m 3.1s"` or `"4.5s"`).
         */
        durationDisplay: String,
        /**
         * Finish reason reported by the model (e.g. `"stop"`, `"length"`).
         */
        finishReason: String
    ) {
        self.text = text
        self.durationSecs = durationSecs
        self.durationDisplay = durationDisplay
        self.finishReason = finishReason
    }

}

#if compiler(>=6)
    extension InferenceResult: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeInferenceResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> InferenceResult
    {
        return
            try InferenceResult(
                text: FfiConverterString.read(from: &buf),
                durationSecs: FfiConverterDouble.read(from: &buf),
                durationDisplay: FfiConverterString.read(from: &buf),
                finishReason: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: InferenceResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterDouble.write(value.durationSecs, into: &buf)
        FfiConverterString.write(value.durationDisplay, into: &buf)
        FfiConverterString.write(value.finishReason, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInferenceResult_lift(_ buf: RustBuffer) throws -> InferenceResult {
    return try FfiConverterTypeInferenceResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInferenceResult_lower(_ value: InferenceResult) -> RustBuffer {
    return FfiConverterTypeInferenceResult.lower(value)
}

/// Configuration for loading an ISQ (in-situ quantised) model via mistral.rs
/// `TextModelBuilder`.
///
/// Unlike GGUF models, ISQ models are loaded directly from a HuggingFace
/// safetensors repo and quantised in-situ on the device.  They require more
/// RAM during the load phase but support a wider range of architectures
/// (e.g. DeepSeek-Coder-V2-Lite, Qwen2.5-Coder-7B).
///
/// **macOS-only for now** — ISQ with Metal acceleration requires the `metal`
/// feature on mistral.rs.  The struct is still defined on all platforms so
/// that types.rs compiles everywhere without `cfg` gates on the record
/// (UniFFI requires all record types to be reachable without feature flags).
public struct IsqModelConfig: Equatable, Hashable {
    /**
     * HuggingFace model repository ID, e.g. `"Qwen/Qwen2.5-Coder-7B-Instruct"`.
     */
    public var modelId: String
    /**
     * Number of quantisation bits.  `4` → Q4K (AFQ4 on Metal), `8` → Q8_0 (AFQ8 on Metal).
     * Any value outside `{4, 8}` defaults to 4-bit.
     */
    public var isqBits: UInt8
    /**
     * Human-friendly display name, e.g. `"Qwen 2.5 Coder 7B"`.
     */
    public var displayName: String
    /**
     * Approximate memory footprint description, e.g. `"~4.5 GB (Q4K, Metal)"`.
     */
    public var approxMemory: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * HuggingFace model repository ID, e.g. `"Qwen/Qwen2.5-Coder-7B-Instruct"`.
         */
        modelId: String,
        /**
         * Number of quantisation bits.  `4` → Q4K (AFQ4 on Metal), `8` → Q8_0 (AFQ8 on Metal).
         * Any value outside `{4, 8}` defaults to 4-bit.
         */
        isqBits: UInt8,
        /**
         * Human-friendly display name, e.g. `"Qwen 2.5 Coder 7B"`.
         */
        displayName: String,
        /**
         * Approximate memory footprint description, e.g. `"~4.5 GB (Q4K, Metal)"`.
         */
        approxMemory: String
    ) {
        self.modelId = modelId
        self.isqBits = isqBits
        self.displayName = displayName
        self.approxMemory = approxMemory
    }

}

#if compiler(>=6)
    extension IsqModelConfig: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeIsqModelConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> IsqModelConfig
    {
        return
            try IsqModelConfig(
                modelId: FfiConverterString.read(from: &buf),
                isqBits: FfiConverterUInt8.read(from: &buf),
                displayName: FfiConverterString.read(from: &buf),
                approxMemory: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: IsqModelConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.modelId, into: &buf)
        FfiConverterUInt8.write(value.isqBits, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.approxMemory, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIsqModelConfig_lift(_ buf: RustBuffer) throws -> IsqModelConfig {
    return try FfiConverterTypeIsqModelConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIsqModelConfig_lower(_ value: IsqModelConfig) -> RustBuffer {
    return FfiConverterTypeIsqModelConfig.lower(value)
}

/// Sampling parameters for text generation.
///
/// All fields are optional — `None` means "use the engine default".
///
/// Note: `usize` is replaced with `u64` for UniFFI compatibility.
public struct SamplingConfig: Equatable, Hashable {
    /**
     * Sampling temperature (higher = more random).  Typical range: 0.0–2.0.
     */
    public var temperature: Double?
    /**
     * Nucleus (top-p) sampling threshold.  Typical value: 0.9–0.95.
     */
    public var topP: Double?
    /**
     * Top-k sampling limit.
     */
    public var topK: UInt64?
    /**
     * Min-p sampling threshold.
     */
    public var minP: Double?
    /**
     * Maximum number of tokens to generate.
     */
    public var maxTokens: UInt64?
    /**
     * Frequency penalty (penalise tokens proportional to occurrence count).
     */
    public var frequencyPenalty: Float?
    /**
     * Presence penalty (penalise tokens that appeared at all).
     */
    public var presencePenalty: Float?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Sampling temperature (higher = more random).  Typical range: 0.0–2.0.
         */
        temperature: Double?,
        /**
         * Nucleus (top-p) sampling threshold.  Typical value: 0.9–0.95.
         */
        topP: Double?,
        /**
         * Top-k sampling limit.
         */
        topK: UInt64?,
        /**
         * Min-p sampling threshold.
         */
        minP: Double?,
        /**
         * Maximum number of tokens to generate.
         */
        maxTokens: UInt64?,
        /**
         * Frequency penalty (penalise tokens proportional to occurrence count).
         */
        frequencyPenalty: Float?,
        /**
         * Presence penalty (penalise tokens that appeared at all).
         */
        presencePenalty: Float?
    ) {
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.minP = minP
        self.maxTokens = maxTokens
        self.frequencyPenalty = frequencyPenalty
        self.presencePenalty = presencePenalty
    }

}

#if compiler(>=6)
    extension SamplingConfig: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSamplingConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> SamplingConfig
    {
        return
            try SamplingConfig(
                temperature: FfiConverterOptionDouble.read(from: &buf),
                topP: FfiConverterOptionDouble.read(from: &buf),
                topK: FfiConverterOptionUInt64.read(from: &buf),
                minP: FfiConverterOptionDouble.read(from: &buf),
                maxTokens: FfiConverterOptionUInt64.read(from: &buf),
                frequencyPenalty: FfiConverterOptionFloat.read(from: &buf),
                presencePenalty: FfiConverterOptionFloat.read(from: &buf)
            )
    }

    public static func write(_ value: SamplingConfig, into buf: inout [UInt8]) {
        FfiConverterOptionDouble.write(value.temperature, into: &buf)
        FfiConverterOptionDouble.write(value.topP, into: &buf)
        FfiConverterOptionUInt64.write(value.topK, into: &buf)
        FfiConverterOptionDouble.write(value.minP, into: &buf)
        FfiConverterOptionUInt64.write(value.maxTokens, into: &buf)
        FfiConverterOptionFloat.write(value.frequencyPenalty, into: &buf)
        FfiConverterOptionFloat.write(value.presencePenalty, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSamplingConfig_lift(_ buf: RustBuffer) throws -> SamplingConfig {
    return try FfiConverterTypeSamplingConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSamplingConfig_lower(_ value: SamplingConfig) -> RustBuffer {
    return FfiConverterTypeSamplingConfig.lower(value)
}

/// A single streaming token chunk from the inference engine.
public struct StreamChunk: Equatable, Hashable {
    /**
     * The token text delta (may be empty for the final chunk).
     */
    public var delta: String
    /**
     * Whether this is the final chunk in the stream.
     */
    public var done: Bool
    /**
     * Finish reason (only set on the final chunk).
     */
    public var finishReason: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The token text delta (may be empty for the final chunk).
         */
        delta: String,
        /**
         * Whether this is the final chunk in the stream.
         */
        done: Bool,
        /**
         * Finish reason (only set on the final chunk).
         */
        finishReason: String?
    ) {
        self.delta = delta
        self.done = done
        self.finishReason = finishReason
    }

}

#if compiler(>=6)
    extension StreamChunk: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamChunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamChunk
    {
        return
            try StreamChunk(
                delta: FfiConverterString.read(from: &buf),
                done: FfiConverterBool.read(from: &buf),
                finishReason: FfiConverterOptionString.read(from: &buf)
            )
    }

    public static func write(_ value: StreamChunk, into buf: inout [UInt8]) {
        FfiConverterString.write(value.delta, into: &buf)
        FfiConverterBool.write(value.done, into: &buf)
        FfiConverterOptionString.write(value.finishReason, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamChunk_lift(_ buf: RustBuffer) throws -> StreamChunk {
    return try FfiConverterTypeStreamChunk.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamChunk_lower(_ value: StreamChunk) -> RustBuffer {
    return FfiConverterTypeStreamChunk.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Role of a message in a chat conversation.
 *
 * Mirrors the standard OpenAI / mistral.rs role taxonomy but is decoupled
 * from `mistralrs::TextMessageRole` so that callers don't need a direct
 * dependency on mistral.rs.
 */

public enum ChatRole: Equatable, Hashable {

    case system
    case user
    case assistant

}

#if compiler(>=6)
    extension ChatRole: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatRole: FfiConverterRustBuffer {
    typealias SwiftType = ChatRole

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatRole {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .system

        case 2: return .user

        case 3: return .assistant

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChatRole, into buf: inout [UInt8]) {
        switch value {

        case .system:
            writeInt(&buf, Int32(1))

        case .user:
            writeInt(&buf, Int32(2))

        case .assistant:
            writeInt(&buf, Int32(3))

        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatRole_lift(_ buf: RustBuffer) throws -> ChatRole {
    return try FfiConverterTypeChatRole.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeChatRole_lower(_ value: ChatRole) -> RustBuffer {
    return FfiConverterTypeChatRole.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Lifecycle status of the inference engine.
 */

public enum EngineStatus: Equatable, Hashable {

    /**
     * No model loaded.
     */
    case unloaded
    /**
     * Model is being downloaded / loaded into memory.
     */
    case loading
    /**
     * Model is loaded and ready to accept requests.
     */
    case ready
    /**
     * Model is currently running inference.
     */
    case generating
    /**
     * An error occurred (model may or may not still be loaded).
     */
    case error

}

#if compiler(>=6)
    extension EngineStatus: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineStatus: FfiConverterRustBuffer {
    typealias SwiftType = EngineStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineStatus
    {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .unloaded

        case 2: return .loading

        case 3: return .ready

        case 4: return .generating

        case 5: return .error

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineStatus, into buf: inout [UInt8]) {
        switch value {

        case .unloaded:
            writeInt(&buf, Int32(1))

        case .loading:
            writeInt(&buf, Int32(2))

        case .ready:
            writeInt(&buf, Int32(3))

        case .generating:
            writeInt(&buf, Int32(4))

        case .error:
            writeInt(&buf, Int32(5))

        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineStatus_lift(_ buf: RustBuffer) throws -> EngineStatus {
    return try FfiConverterTypeEngineStatus.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineStatus_lower(_ value: EngineStatus) -> RustBuffer {
    return FfiConverterTypeEngineStatus.lower(value)
}

/// Errors that can occur during inference engine operations.
///
/// Exposed to Swift / Kotlin as a sealed class / enum via `uniffi::Error`.
public enum InferenceError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    case NoModelLoaded
    case AlreadyLoaded(
        modelName: String
    )
    case ModelBuild(
        reason: String
    )
    case Inference(
        reason: String
    )
    case Cancelled
    case Other(
        reason: String
    )

    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
    extension InferenceError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeInferenceError: FfiConverterRustBuffer {
    typealias SwiftType = InferenceError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> InferenceError
    {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .NoModelLoaded
        case 2:
            return .AlreadyLoaded(
                modelName: try FfiConverterString.read(from: &buf)
            )
        case 3:
            return .ModelBuild(
                reason: try FfiConverterString.read(from: &buf)
            )
        case 4:
            return .Inference(
                reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Cancelled
        case 6:
            return .Other(
                reason: try FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: InferenceError, into buf: inout [UInt8]) {
        switch value {

        case .NoModelLoaded:
            writeInt(&buf, Int32(1))

        case .AlreadyLoaded(let modelName):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(modelName, into: &buf)

        case .ModelBuild(let reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)

        case .Inference(let reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)

        case .Cancelled:
            writeInt(&buf, Int32(5))

        case .Other(let reason):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(reason, into: &buf)

        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInferenceError_lift(_ buf: RustBuffer) throws -> InferenceError {
    return try FfiConverterTypeInferenceError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInferenceError_lower(_ value: InferenceError) -> RustBuffer {
    return FfiConverterTypeInferenceError.lower(value)
}

/// Callback interface for receiving streaming token chunks.
///
/// Implement this in Swift / Kotlin and pass it to the free function
/// [`stream_chat_message`].
///
/// ```swift
/// class MyStreamHandler: StreamChunkListener {
/// func onChunk(chunk: StreamChunk) -> Bool {
/// print(chunk.delta, terminator: "")
/// return !chunk.done  // return false to stop early
/// }
/// }
/// ```
public protocol StreamChunkListener: AnyObject, Sendable {

    /**
     * Called for each token chunk during streaming inference.
     *
     * Return `true` to continue receiving chunks, or `false` to cancel
     * the stream early (the engine will still persist partial history).
     */
    func onChunk(chunk: StreamChunk) -> Bool

}

// Put the implementation in a struct so we don't pollute the top-level namespace
private struct UniffiCallbackInterfaceStreamChunkListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceStreamChunkListener] = [
        UniffiVTableCallbackInterfaceStreamChunkListener(
            uniffiFree: { (uniffiHandle: UInt64) -> Void in
                do {
                    try FfiConverterCallbackInterfaceStreamChunkListener.handleMap.remove(
                        handle: uniffiHandle)
                } catch {
                    print(
                        "Uniffi callback interface StreamChunkListener: handle missing in uniffiFree"
                    )
                }
            },
            uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
                do {
                    return try FfiConverterCallbackInterfaceStreamChunkListener.handleMap.clone(
                        handle: uniffiHandle)
                } catch {
                    fatalError(
                        "Uniffi callback interface StreamChunkListener: handle missing in uniffiClone"
                    )
                }
            },
            onChunk: {
                (
                    uniffiHandle: UInt64,
                    chunk: RustBuffer,
                    uniffiOutReturn: UnsafeMutablePointer<Int8>,
                    uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
                ) in
                let makeCall = {
                    () throws -> Bool in
                    guard
                        let uniffiObj =
                            try? FfiConverterCallbackInterfaceStreamChunkListener.handleMap.get(
                                handle: uniffiHandle)
                    else {
                        throw UniffiInternalError.unexpectedStaleHandle
                    }
                    return uniffiObj.onChunk(
                        chunk: try FfiConverterTypeStreamChunk_lift(chunk)
                    )
                }

                let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
                uniffiTraitInterfaceCall(
                    callStatus: uniffiCallStatus,
                    makeCall: makeCall,
                    writeReturn: writeReturn
                )
            }
        )
    ]
}

private func uniffiCallbackInitStreamChunkListener() {
    uniffi_onde_fn_init_callback_vtable_streamchunklistener(
        UniffiCallbackInterfaceStreamChunkListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterCallbackInterfaceStreamChunkListener {
    fileprivate static let handleMap = UniffiHandleMap<StreamChunkListener>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceStreamChunkListener: FfiConverter {
    typealias SwiftType = StreamChunkListener
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceStreamChunkListener_lift(_ handle: UInt64) throws
    -> StreamChunkListener
{
    return try FfiConverterCallbackInterfaceStreamChunkListener.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceStreamChunkListener_lower(_ v: StreamChunkListener)
    -> UInt64
{
    return FfiConverterCallbackInterfaceStreamChunkListener.lower(v)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeSamplingConfig: FfiConverterRustBuffer {
    typealias SwiftType = SamplingConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSamplingConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSamplingConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0..<len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer {
    typealias SwiftType = [ChatMessage]

    public static func write(_ value: [ChatMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> [ChatMessage]
    {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0..<len {
            seq.append(try FfiConverterTypeChatMessage.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

private let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

private func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> Void,
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> Void,
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureOndeInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(
        makeRustCall(
            { completeFunc(rustFuture, $0) },
            errorHandler: errorHandler
        ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
private func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/// Create an assistant message.
public func assistantMessage(content: String) -> ChatMessage {
    return try! FfiConverterTypeChatMessage_lift(
        try! rustCall {
            uniffi_onde_fn_func_assistant_message(
                FfiConverterString.lower(content), $0
            )
        })
}
/// Return the platform-appropriate default GGUF model configuration.
///
/// - tvOS / iOS / Android → Qwen 2.5 1.5B (~941 MB)
/// - macOS / Windows / Linux → Qwen 2.5 3B (~1.93 GB)
public func defaultModelConfig() -> GgufModelConfig {
    return try! FfiConverterTypeGgufModelConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_default_model_config(
                $0
            )
        })
}
/// Return default sampling parameters for creative chat.
public func defaultSamplingConfig() -> SamplingConfig {
    return try! FfiConverterTypeSamplingConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_default_sampling_config(
                $0
            )
        })
}
/// Return deterministic (greedy) sampling parameters.
public func deterministicSamplingConfig() -> SamplingConfig {
    return try! FfiConverterTypeSamplingConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_deterministic_sampling_config(
                $0
            )
        })
}
/// Return conservative sampling parameters for mobile devices.
public func mobileSamplingConfig() -> SamplingConfig {
    return try! FfiConverterTypeSamplingConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_mobile_sampling_config(
                $0
            )
        })
}
/// Return the Qwen 2.5 1.5B GGUF model configuration (~941 MB).
public func qwen2515bConfig() -> GgufModelConfig {
    return try! FfiConverterTypeGgufModelConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_qwen25_1_5b_config(
                $0
            )
        })
}
/// Return the Qwen 2.5 3B GGUF model configuration (~1.93 GB).
public func qwen253bConfig() -> GgufModelConfig {
    return try! FfiConverterTypeGgufModelConfig_lift(
        try! rustCall {
            uniffi_onde_fn_func_qwen25_3b_config(
                $0
            )
        })
}
/// Stream a chat message through the engine, delivering token chunks to
/// the `listener` callback.
///
/// This is a **free function** (not an Object method) because UniFFI 0.31
/// requires `callback_interface` parameters to be passed to free functions
/// rather than Object methods.
///
/// The `listener.on_chunk()` callback is called for each token delta.
/// Return `true` to continue, or `false` to cancel early.
///
/// The user message and assembled reply are automatically appended to the
/// engine's conversation history when streaming completes.
///
/// ```swift
/// class MyHandler: StreamChunkListener {
/// func onChunk(chunk: StreamChunk) -> Bool {
/// print(chunk.delta, terminator: "")
/// return !chunk.done
/// }
/// }
///
/// try await streamChatMessage(
/// engine: engine,
/// message: "Tell me a story.",
/// listener: MyHandler()
/// )
/// ```
public func streamChatMessage(
    engine: OndeChatEngine, message: String, listener: StreamChunkListener
) async throws {
    return
        try await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_onde_fn_func_stream_chat_message(
                    FfiConverterTypeOndeChatEngine_lower(engine), FfiConverterString.lower(message),
                    FfiConverterCallbackInterfaceStreamChunkListener_lower(listener)
                )
            },
            pollFunc: ffi_onde_rust_future_poll_void,
            completeFunc: ffi_onde_rust_future_complete_void,
            freeFunc: ffi_onde_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeInferenceError_lift
        )
}
/// Create a system message.
public func systemMessage(content: String) -> ChatMessage {
    return try! FfiConverterTypeChatMessage_lift(
        try! rustCall {
            uniffi_onde_fn_func_system_message(
                FfiConverterString.lower(content), $0
            )
        })
}
/// Create a user message.
public func userMessage(content: String) -> ChatMessage {
    return try! FfiConverterTypeChatMessage_lift(
        try! rustCall {
            uniffi_onde_fn_func_user_message(
                FfiConverterString.lower(content), $0
            )
        })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_onde_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_onde_checksum_func_assistant_message() != 47135 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_default_model_config() != 34766 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_default_sampling_config() != 57358 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_deterministic_sampling_config() != 3003 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_mobile_sampling_config() != 46137 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_qwen25_1_5b_config() != 41668 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_qwen25_3b_config() != 36458 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_stream_chat_message() != 5168 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_system_message() != 55655 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_func_user_message() != 23108 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_clear_history() != 5662 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_clear_system_prompt() != 46275 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_generate() != 63069 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_history() != 45301 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_info() != 42415 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_is_loaded() != 59838 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_load_default_model() != 32187 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_load_gguf_model() != 6873 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_push_history() != 61696 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_send_message() != 23695 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_set_sampling() != 10759 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_set_system_prompt() != 63168 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_ondechatengine_unload_model() != 33799 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_constructor_ondechatengine_new() != 39683 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_onde_checksum_method_streamchunklistener_on_chunk() != 33920 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitStreamChunkListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOndeInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
